### ISSUE TITLE
Using albumArtMatrix with a ICND2153 64x64 matrix

### ISSUE THREAD

**Issue by lohant** [witnessmenow/spotify-api-arduino#57]
Hi,

I'm happily using the albumArtMatrix example with one om my matrices. However, I would like to use it with my new matrix that uses the ICND21153 IC. I am using the following library to control it: https://github.com/LAutour/ESP32-HUB75-MatrixPanel-DMA-ICN2053

When I plugged it in, this did not compile: `dma_display->fillScreen(dma_display->color565(0,` 0, `0));`

Furthermore, when I commented the problematic rows out, the code compiled but the album art does not show up. I have previously modified the code to work with this library: https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA
I suspect that there is something that needs to be changed in the following function now:

`// This next function will be called during decoding of the jpeg file to`
`// render each block to the Matrix.  If you use a different display`
`// you will need to adapt this function to suit.`

`int JPEGDraw(JPEGDRAW *pDraw) {`
`  // Stop further decoding as image is running off bottom of screen`
`  if (  pDraw->y >= dma_display->height() ) return 1;`

`  dma_display->drawRGBBitmap(pDraw->x, pDraw->y, pDraw->pPixels, pDraw->iWidth, pDraw->iHeight);`
` return 1;`
`}`

I would be very thankful if anyone could point me in the right direction to make this work. Thanks!

**Comment by witnessmenow** [comment]
From a very quick look, I don't see why it wouldn't work. I havent played around with that example in a while. And have even changed the JPEG displaying library I normally use since.

This is a very similar project I have updated in the last few months that uses the different JPEG library. 
https://github.com/witnessmenow/Spotify-NFC-Matrix-Display

It has an additional NFC element to it that you could maybe just comment out, or just install whatever is needed and allow it to fail to initialize (it should keep working without it)

**Comment by pablomofo1** [comment]
Can you tell me what version of library you used?

**Comment by witnessmenow** [comment]
I don't believe this issue really relates to the library, the library is designed to be completely independent of displays
